---
# This playbook does following:
#   enables Percona testing repository
#   installs PSMDB 3.4
#   does some tests

- hosts: pkg-test

  tasks:
  - name: include tasks for test env setup
    include: ../tasks/test_prep.yml

  - name: include tasks for enabling test repo
    include: ../tasks/enable_testing_repo.yml

  - name: install Percona Server for MongoDB 3.4 new deb packages
    apt: name={{item}} update_cache=yes state=latest
    with_items:
    - percona-server-mongodb-34
    - percona-server-mongodb-34-dbg
    when: ansible_os_family == "Debian"

  - name: install Percona Server for MongoDB 3.4 new rpm packages
    yum: name={{item}} state=latest
    with_items:
    - Percona-Server-MongoDB-34
    - Percona-Server-MongoDB-34-debuginfo
    when: ansible_os_family == "RedHat"

  - name: start mongod with init script
    command: /etc/init.d/mongod start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

  - name: start mongod with service
    command: service mongod start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: start mongod with systemctl
    command: systemctl start mongod
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: check that PSMDB 3.4 package versions are correct
    command: /package-testing/package_check.sh psmdb34

  - name: test SE change, import data, restart service
    command: /package-testing/psmdb_test.sh 3.4
