---
# This playbook does following:
#   sets main Percona repo
#   installs PSMDB 3.0
#   changes repo to testing
#   upgrades packages to the new version
#   does some tests

- hosts: pkg-test

  tasks:
  - name: include tasks for test env setup
    include: ../tasks/test_prep.yml

#
# Install from main repository
#
  - name: include tasks for enabling main repo
    include: ../tasks/enable_main_repo.yml

  - name: install Percona Server for MongoDB 3.0 deb packages previous version
    apt: name={{item}} update_cache=yes state=latest
    with_items:
    - percona-server-mongodb
    - percona-server-mongodb-dbg
    when: ansible_os_family == "Debian"

  - name: install Percona Server for MongoDB 3.0 new rpm packages previous version
    yum: name={{item}} state=latest
    with_items:
    - Percona-Server-MongoDB
    - Percona-Server-MongoDB-debuginfo
    when: ansible_os_family == "RedHat"

  - name: start mongod with init script
    command: /etc/init.d/mongod start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

  - name: start mongod with service
    command: service mongod start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: start mongod with systemctl
    command: systemctl start mongod
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

#
# Enable testing repository
#
  - include: ../tasks/enable_testing_repo.yml

#
# Upgrade packages
#
  - name: upgrade Percona Server for MongoDB 3.0 to new deb packages
    apt: name={{item}} update_cache=yes state=latest
    with_items:
    - percona-server-mongodb
    - percona-server-mongodb-server
    - percona-server-mongodb-mongos
    - percona-server-mongodb-shell
    - percona-server-mongodb-tools
    - percona-server-mongodb-dbg
    when: ansible_os_family == "Debian"

  - name: upgrade Percona Server for MongoDB 3.0 to new rpm packages
    yum: name={{item}} state=latest
    with_items:
    - Percona-Server-MongoDB
    - Percona-Server-MongoDB-server
    - Percona-Server-MongoDB-shell
    - Percona-Server-MongoDB-mongos
    - Percona-Server-MongoDB-tools
    - Percona-Server-MongoDB-debuginfo
    when: ansible_os_family == "RedHat"

  - name: check that PSMDB 3.0 package versions are correct
    command: /package-testing/package_check.sh psmdb30

  - name: test SE change, import data, restart service
    command: /package-testing/psmdb_test.sh 3.0
