---
# This playbook upgrades the PXC node to the latest available version in testing repo

- hosts: pkg-test

  tasks:
  - name: include tasks for enabling testing repo
    include: ../tasks/enable_testing_repo.yml

  - name: upgrade PXC 5.6 to new deb packages
    apt: name={{item}} update_cache=yes
    with_items:
    - percona-xtradb-cluster-full-56
    - percona-xtradb-cluster-test-5.6
    - percona-xtradb-cluster-source-5.6
    - percona-xtradb-cluster-server-debug-5.6
    - percona-xtradb-cluster-server-5.6
    - percona-xtradb-cluster-galera3-dbg
    - percona-xtradb-cluster-galera-3
    - percona-xtradb-cluster-common-5.6
    - percona-xtradb-cluster-client-5.6
    - percona-xtradb-cluster-5.6-dbg
    - percona-xtradb-cluster-56
    when: ansible_os_family == "Debian"

  - name: upgrade PXC 5.6 to new rpm packages
    yum: name={{item}} state=latest
    with_items:
    - Percona-XtraDB-Cluster-full-56
    - Percona-XtraDB-Cluster-client-56
    - Percona-XtraDB-Cluster-devel-56
    - Percona-XtraDB-Cluster-galera-3-debuginfo
    - Percona-XtraDB-Cluster-galera-3
    - Percona-XtraDB-Cluster-devel-56
    - Percona-XtraDB-Cluster-client-56
    - Percona-XtraDB-Cluster-shared-56
    - Percona-XtraDB-Cluster-test-56
    - Percona-XtraDB-Cluster-garbd-3
    - Percona-XtraDB-Cluster-56-debuginfo
    - Percona-XtraDB-Cluster-56
    when: ansible_os_family == "RedHat"

  - name: check that PXC version is correct
    command: /package-testing/version_check.sh pxc56

  - name: check that PXC package versions are correct
    command: /package-testing/package_check.sh pxc56
