---
# This playbook upgrades the PXC node to the latest available version in testing repo

- hosts: pkg-test

  tasks:
  - name: include tasks for enabling testing repo
    include: ../tasks/enable_testing_repo.yml

  - name: upgrade PXC 5.7 to new deb packages
    apt: name={{item}} update_cache=yes
    with_items:
    - percona-xtradb-cluster-full-57
    - percona-xtradb-cluster-test-5.7
    - percona-xtradb-cluster-source-5.7
    - percona-xtradb-cluster-server-debug-5.7
    - percona-xtradb-cluster-server-5.7
    - percona-xtradb-cluster-common-5.7
    - percona-xtradb-cluster-5.7-dbg
    - percona-xtradb-cluster-client-5.7
    - percona-xtradb-cluster-57
    when: ansible_os_family == "Debian"

  - name: upgrade PXC 5.7 to new rpm packages
    yum: name={{item}} state=latest
    with_items:
    - Percona-XtraDB-Cluster-full-57
    - Percona-XtraDB-Cluster-test-57
    - Percona-XtraDB-Cluster-shared-57
    - Percona-XtraDB-Cluster-server-57
    - Percona-XtraDB-Cluster-garbd-57
    - Percona-XtraDB-Cluster-devel-57
    - Percona-XtraDB-Cluster-client-57
    - Percona-XtraDB-Cluster-57-debuginfo
    - Percona-XtraDB-Cluster-57
    when: ansible_os_family == "RedHat"

  - name: check that PXC version is correct
    command: /package-testing/version_check.sh pxc57

  - name: check that PXC package versions are correct
    command: /package-testing/package_check.sh pxc57
