---
# This playbook sets up the percona testing repo and upgrades all the packages

- hosts: pkg-test

  tasks:
  - name: include tasks for enabling testing repo
    include: ../tasks/enable_testing_repo.yml

  - name: upgrade deb packages
    apt: update_cache=yes upgrade=safe
    when: ansible_os_family == "Debian"

  - name: upgrade packages in centos
    yum: name=* state=latest
    when: ansible_os_family == "RedHat"
